# Οι μεταβλητές ορίζονται στο αρχείο .env
services:
  postgres:
    image: postgres:latest
    container_name: icsauthdb
    restart: unless-stopped 
    volumes:
      - icsauth-volume:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - ics-network

  keycloak:
    # Εδώ έχω μαζέψει όλα που κατά καιρούς έχω διαβάσει σε διάφορα άρθρα με βασικό οδηγό το official documentation του keycloak
    # Running Keycloak in a container [https://www.keycloak.org/server/containers]
    image: keycloak:26.7.4-r1
    build:
      context: .
      dockerfile: ../../../images/keycloak/Dockerfile
    container_name: icsauth
    depends_on:
      - postgres
      - caddy
    environment:
      # Admin Credentials (https://www.keycloak.org/docs/latest/server_admin/index.html#creating-the-account-remotely)
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      # Database runtime Configuration Options
      KC_DB_URL: 'jdbc:postgresql://postgres/keycloak'
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
    #PROXY_ADDRESS_FORWARDING: "true"
    command:
      - start
      - --optimized
      - --hostname=https://icsauth.net
      - --http-enabled=true
      - --proxy-headers=xforwarded
    #  [
    #    'start',
    #    '--optimized',
    #    '--proxy edge',
    #    '--proxy-headers forwarded',
    #    '--hostname https://icsauth.net'
    #  ]
    restart: always
    # Δε χρειάζεται να κάνω export ports του keycloak στον host. Ο caddy αναλαμβάνει το forwarding στο keycloak μέσω του docker network
    #ports:
    networks:
      - ics-network

  caddy:
    image: caddy:2.11.4-r1
    build:
      context: .
      dockerfile: ../../../images/caddy/Dockerfile
    container_name: icsproxy
    restart: unless-stopped
    environment:
      CF_API_TOKEN: ${CF_API_TOKEN}
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    #  - "2019:2019" # Caddy Admin API (deprecated)
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      #- ./site:/srv
      - icsproxy-volume:/data
      - icsproxy-conf-volume:/config
    networks:
      - ics-network

volumes:
  icsauth-volume:
    name: icsauth-volume
  icsproxy-volume:
    name: icsproxy-volume
  icsproxy-conf-volume:
    name: icsproxy-conf-volume 

networks:
  ics-network:
    name: ics-network
    