services:
  openbao:
    image: openbao/openbao:2.5.4
    container_name: icscert
    restart: unless-stopped

    command: server -config=/etc/openbao/bao.hcl

    cap_add:
      - IPC_LOCK

    volumes:
      - icscert-srv-data:/openbao/data
      - ./config/bao.hcl:/etc/openbao/bao.hcl:ro
    networks:
      - ics-network

volumes:
  icscert-srv-data:
    name: icscert-srv-data

networks:
  ics-network:
    name: ics-network