services:
  openbao:
    image: openbao/openbao:2.5.4
    container_name: icscert
    restart: unless-stopped

    command: server -config=/etc/openbao/bao.hcl

    cap_add:
      - IPC_LOCK

    volumes:
      - icscert-volume:/openbao/data
      - ./config/bao.hcl:/etc/openbao/bao.hcl:ro
    tmpfs:
      - /openbao/file
      - /openbao/logs
    networks:
      - ics-network

volumes:
  icscert-volume:
    name: icscert-volume

networks:
  ics-network:
    external: true
    name: ics-network