services:
  caddy:
    image: caddy:latest
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
      - "443:443/udp"
    #- "2019:2019"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      #- ./site:/srv
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - ics-network

volumes:
  caddy_data:
  caddy_config:

networks:
  ics-network:
    name: ics-network